version: '3.1'

services:
  db:
    container_name: bookstoreDb
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_DB: bookstore
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: pass123
    ports:
      - 7432:5432